name: zakey_assistant
description: "Zakey Full Voice Assistant"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.7+1
  url_launcher: ^6.2.5
  installed_apps: ^1.5.0
  notification_listener_service: ^0.3.0

flutter:
  uses-material-design: true
